#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: Sai Supraja Mutnuru | Course: Open Source Software
echo "Answer three questions to generate your manifesto."
echo ""
# User Input 
read -p "1. Name one open-source tool you use every day: " TOOL
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD

# Date and Output File 
DATE=$(date '+%d %B %Y')   # Current date 
OUTPUT="manifesto_$(whoami).txt"   # Output file 

# Paragraph Composing
# Using string concatenation 
echo "----------------------------------------" > "$OUTPUT"
echo " Open Source Manifesto" >> "$OUTPUT"
echo "----------------------------------------" >> "$OUTPUT"
echo "Date: $DATE" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo " $TOOL is a modern software tool" >> "$OUTPUT"
echo "Freedom means $FREEDOM" >> "$OUTPUT"
echo "I would build $BUILD and share it openly so others can benefit and improve it" >> "$OUTPUT"
echo "I think knowledge grows when it is shared, and open source is the basis of that belief" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Generated by $(whoami) on $DATE" >> "$OUTPUT"

#  Output Message 
echo ""
echo "Manifesto saved to $OUTPUT"
echo ""

# File Content 
cat "$OUTPUT"
